# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180718_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
