# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='check_assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Check'),
            preserve_default=False,
        ),
    ]
