# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180710_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(default='monthly', max_length=20),
        ),
    ]
