# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        ('accounts', '0009_auto_20180710_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_checks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Check'),
        ),
    ]
