# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_profile_checks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_checks',
        ),
    ]
