# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180711_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='check_assigned',
            field=models.ManyToManyField(to='api.Check'),
        ),
    ]
