# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180712_0438'),
        ('accounts', '0008_auto_20180712_0708'),
    ]

    operations = [
    ]
