# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20180712_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scheduled_task_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 8, 14, 0, 65341, tzinfo=utc)),
        ),
    ]
