# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_member_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='priority',
        ),
    ]
