# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_member_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
