# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180718_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 13, 55, 13, 758615, tzinfo=utc)),
        ),
    ]
