# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180712_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='new_nag_after',
            field=models.DurationField(default=datetime.timedelta(1, 3600)),
        ),
    ]
