# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_new_nag_after'),
        ('api', '0030_remove_check_profile'),
    ]

    operations = [
    ]
