# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20180713_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='priority',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'normal'), (2, 'high')], default=1),
        ),
    ]
