# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20180713_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
