# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_merge_20180713_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(default='* * * * *', max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('body', models.CharField(blank=True, max_length=100)),
                ('task_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
