# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180716_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='department',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
