# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
