# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180719_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='prev_alert_status',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
